/// Flutter icons OvermorrowWeatherIcons3
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OvermorrowWeatherIcons3
///      fonts:
///       - asset: fonts/OvermorrowWeatherIcons3.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OvermorrowWeatherIcons3 {
  OvermorrowWeatherIcons3._();

  static const _kFontFam = 'OvermorrowWeatherIcons3';
  static const String? _kFontPkg = null;

  static const IconData partly_cloudy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy_night = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heavy_rain = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_sky = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_night = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunderstorm = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleet = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heavy_snow = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fog = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData haze = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
