/*
Copyright (C) <2024>  <Balint Maroti>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

*/

Map<String, int> languageIndex = { //the index of the language used in the mainTranslate
  'English' : 0,
  'Magyar' : 1,
  'Español' : 2,
  'Français' : 3,
  'Deutsch' : 4,
  'Italiano' : 5,
  'Português' : 6,
  'Русский' : 7,
  '简体中文' : 8,
  '日本語' : 9,
  'Polski' : 10,
  'Ελληνικά' : 11
};

Map<String, List<String>> mainTranslate = {
  'Feels like': [
    'Feels like',
    'Hőérzet',
    'Sensación',
    'Ressenti',
    'Gefühlt',
    'Percepito',
    'Sensação',
    'Ощущается',
    '体感',
    '体感',
    'Odczuwaln.',
    'Αίσθηση'
  ],
  'Precip.': [
    'Precip.',
    'Csapad.',
    'Precip.',
    'Précip.',
    'Niedersch.',
    'Precip.',
    'Precip.',
    'Осадки',
    '降水',
    '降水',
    'Opady',
    'Κατ. βροχ.'
  ],
  'Humidity': [
    'Humidity',
    'Páratart.',
    'Humedad',
    'Humidité',
    'Luftfeuch.',
    'Umidità',
    'Humidade',
    'Влажность',
    '湿度',
    '湿度',
    'Wilgot.',
    'Υγρασία'
  ],
  'Wind': [
    'Wind',
    'Szél',
    'Viento',
    'Vent',
    'Wind',
    'Vento',
    'Vento',
    'Ветер',
    '风',
    '風',
    'Wiatr',
    'Άνεμος'
  ],
  'UV': [
    'UV',
    'UV',
    'UV',
    'UV',
    'UV',
    'UV',
    'UV',
    'УФ',
    '紫外线',
    'UV',
    'UV',
    'UV'
  ],
  'precip.': [
    'Precip.',
    'Csapadék',
    'Precip.',
    'Précip.',
    'Niederschlag',
    'Precipitazione',
    'Precip.',
    'Осадки',
    '降水',
    '降水量',
    'Opady',
    'Βροχόπτωση'
  ],
  'Settings': [
    'Settings',
    'Beállítások',
    'Configuración',
    'Paramètres',
    'Einstellungen',
    'Impostazioni',
    'Configurações',
    'Настройки',
    '设置',
    '設定',
    'Ustawienia',
    'Ρυθμίσεις'
  ],
  'Donate': [
    'Donate',
    'Adományozás',
    'Donar',
    'Donner',
    'Spenden',
    'Dona',
    'Doar',
    'Пожертвовать',
    '捐赠',
    '寄付',
    'Wesprzyj',
    'Κάντε δωρεά'
  ],
  'About': [
    'About',
    'Névjegy',
    'Acerca de',
    'À propos de',
    'Über',
    'Informazioni',
    'Sobre',
    'О программе',
    '关于',
    '紹介',
    'Info',
    'Σχετικά με'
  ],
  'Today': [
    'Today',
    'Ma',
    'Hoy',
    'Aujourd hui',
    'Heute',
    'Oggi',
    'Hoje',
    'Сегодня',
    '今天',
    '今日',
    'Dzisiaj',
    'Σήμερα'
  ],
  'Tomorrow': [
    'Tomorrow',
    'Holnap',
    'Mañana',
    'Demain',
    'Morgen',
    'Domani',
    'Amanhã',
    'Завтра',
    '明天',
    '明日',
    'Jutro',
    'Αύριο'
  ],
  'Overmorrow': [
    'Overmorrow',
    'Holnapután',
    'Pasado Mañana',
    'Après-demain',
    'Übermorgen',
    'Dopodomani',
    'Depois de Amanhã',
    'Послезавтра',
    '后天',
    '明後日',
    'Pojutrze',
    'Μεθαύριο'
  ],
  'Language': [
    'Language',
    'Nyelv',
    'Idioma',
    'Langue',
    'Sprache',
    'Lingua',
    'Língua',
    'Язык',
    '语言',
    '言語',
    'Język',
    'Γλώσσα'
  ],
  'Temperature': [
    'Temperature',
    'Hőmérséklet',
    'Temperatura',
    'Température',
    'Temperatur',
    'Temperatura',
    'Temperatura',
    'Температура',
    '温度',
    '気温',
    'Temperatura',
    'Θερμοκρασία'
  ],
  'Rain': [
    'Rain',
    'Eső',
    'Lluvia',
    'Pluie',
    'Regen',
    'Pioggia',
    'Chuva',
    'Дождь',
    '雨',
    '雨',
    'Deszcz',
    'Βροχή'
  ],
  'Precipitation': [
    'Precipitation',
    'Csapadék',
    'Precipitación',
    'Précipitation',
    'Niederschlag',
    'Precipitazione',
    'Precipitação',
    'Осадки',
    '降水量',
    '降水',
    'Opady',
    'Βροχόπτωση'
  ],
  'Favorites': [
    'Favorites',
    'Kedvencek',
    'Favoritos',
    'Favoris',
    'Favoriten',
    'Preferiti',
    'Favoritos',
    'Избранное',
    '收藏夹',
    'お気に入り',
    'Ulubione',
    'Αγαπημένα'
  ],
  'Clear Night': [
    'Clear Night',
    'Tiszta éjszaka',
    'Noche despejada',
    'Nuit claire',
    'Klare Nacht',
    'Notte serena',
    'Noite limpa',
    'Чистая ночь',
    '晴朗的夜晚',
    '快晴の夜',
    'Bezchmurna noc',
    'Καθαρή Βραδυά'
  ],
  'Partly Cloudy': [
    'Partly Cloudy',
    'Részben felhős',
    'Parcialmente nublado',
    'Partiellement nuageux',
    'Teils wolkig',
    'Parzialmente nuvoloso',
    'Parcialmente nublado',
    'Частичная облачность',
    '局部多云',
    '一部曇り',
    'Częściowe zachmurzenie',
    'Αραιή Συννεφιά'
  ],
  'Clear Sky': [
    'Clear Sky',
    'Tiszta ég',
    'Cielo despejado',
    'Ciel clair',
    'Klarer Himmel',
    'Cielo sereno',
    'Céu limpo',
    'Чистое небо',
    '晴朗的天空',
    '快晴',
    'Bezchmurnie',
    'Καθαρός Ουρανός'
  ],
  'Overcast': [
    'Overcast',
    'Borult',
    'Nublado',
    'Couvert',
    'Bedeckt',
    'Coperto',
    'Nublado',
    'Пасмурно',
    '阴天',
    '曇り',
    'Zachmurzenie',
    'Νεφελώδης'
  ],
  'Haze': [
    'Haze',
    'Köd',
    'Niebla',
    'Brume',
    'Dunst',
    'Foschia',
    'Neblina',
    'Туман',
    '雾霾',
    '霧',
    'Mglisto',
    'Ομίχλη'
  ],
  'Sleet': [
    'Sleet',
    'Hószitálás',
    'Aguanieve',
    'Neige fondue',
    'Schneeregen',
    'Pioggia congelata',
    'Chuva congelada',
    'Мокрый снег',
    '雨夹雪',
    'みぞれ',
    'Deszcz ze śniegiem',
    'Χιονόνερο'
  ],
  'Drizzle': [
    'Drizzle',
    'Szemerkél',
    'Llovizna',
    'Bruine',
    'Nieselregen',
    'Pioggerella',
    'Chuvisco',
    'Морось',
    '毛毛雨',
    '霧雨',
    'Mżawka',
    'Ψιχάλα'
  ],
  'Thunderstorm': [
    'Thunderstorm',
    'Zivatar',
    'Tormenta',
    'Orage',
    'Gewitter',
    'Temporale',
    'Tempestade',
    'Гроза',
    '雷暴',
    '雷雨',
    'Burza',
    'Καταιγίδα'
  ],
  'Heavy Snow': [
    'Heavy Snow',
    'Hóvihar',
    'Nevada intensa',
    'Forte neige',
    'Starker Schneefall',
    'Forte nevicata',
    'Neve intensa',
    'Сильный снег',
    '大雪',
    '大雪',
    'Śnieżyca',
    'Βαριά Χιονόπτωση'
  ],
  'Fog': [
    'Fog',
    'Köd',
    'Nebbia',
    'Brouillard',
    'Nebel',
    'Nebbia',
    'Nevoeiro',
    'Туман',
    '雾',
    '霧',
    'Mgła',
    'Ομίχλη'
  ],
  'Snow': [
    'Snow',
    'Hó',
    'Nieve',
    'Neige',
    'Schnee',
    'Neve',
    'Neve',
    'Снег',
    '雪',
    '雪',
    'Opady śniegu',
    'Χιονόπτωση'
  ],
  'Heavy Rain': [
    'Heavy Rain',
    'Erős eső',
    'Lluvia intensa',
    'Pluie forte',
    'Starker Regen',
    'Pioggia intensa',
    'Chuva intensa',
    'Сильный дождь',
    '大雨',
    '大雨',
    'Ulewa',
    'Δυνατή Βροχή'
  ],
  'Cloudy Night': [
    'Cloudy Night',
    'Felhős éjszaka',
    'Noche nublada',
    'Nuit nuageuse',
    'Bewölkte Nacht',
    'Notte nuvolosa',
    'Noite nublada',
    'Облачная ночь',
    '多云的夜晚',
    '多云の夜',
    'Pochmurna noc',
    'Συννεφιασμένη Νύχτα'
  ],

  'Weak or no wifi connection': [
    'Weak or no wifi connection',
    'Gyenge vagy nincs wifi kapcsolat',
    'Conexión wifi débil o inexistente',
    'Connexion Wi-Fi faible ou inexistante',
    'Schwache oder keine WLAN-Verbindung',
    'Connessione Wi-Fi debole o assente',
    'Conexão Wi-Fi fraca ou inexistente',
    'Слабое или отсутствующее подключение Wi-Fi',
    '无线网络信号弱或无连接',
    'Wi-Fi接続が弱いかありません',
    'Słabe połączenie lub brak Wi-Fi',
    'Αδύναμη ή χωρίς σύνδεση Wi-Fi'
  ],
  'Not connected to the internet': [
    'Not connected to the internet',
    'Nincs internetkapcsolat',
    'No conectado a internet',
    'Pas connecté à Internet',
    'Nicht mit dem Internet verbunden',
    'Non connesso a Internet',
    'Não conectado à internet',
    'Нет подключения к Интернету',
    '未连接到互联网',
    'インターネットに接続されていません',
    'Brak internetu',
    'Χωρίς σύνδεση στο διαδίκτυο'
  ],
  'Place not found': [
    'Place not found',
    'Hely nem található',
    'Lugar no encontrado',
    'Lieu non trouvé',
    'Ort nicht gefunden',
    'Luogo non trovato',
    'Local não encontrado',
    'Место не найдено',
    '未找到地点',
    '場所が見つかりません',
    'Nie znaleziono lokalizacji',
    'Δεν βρέθηκε η τοποθεσία'
  ],
  'Unable to locate device': [
    'Unable to locate device',
    'Nem sikerült megtalálni az eszközt',
    'No se puede localizar el dispositivo',
    'Impossible de localiser l appareil',
    'Gerät kann nicht gefunden werden',
    'Impossibile localizzare il dispositivo',
    'Não é possível localizar o dispositivo',
    'Не удается найти устройство',
    '无法定位设备',
    'デバイスを特定できません',
    'Brak możliwości zlokalizowania urządzenia',
    'Η συσκευή δεν εντοπίστηκε'
  ],
  'location services are disabled.': [
    'location services are disabled.',
    'A helymeghatározás szolgáltatások kikapcsolva vannak.',
    'Los servicios de ubicación están desactivados.',
    'Les services de localisation sont désactivés.',
    'Standortdienste sind deaktiviert.',
    'I servizi di localizzazione sono disattivati.',
    'Os serviços de localização estão desativados.',
    'Сервисы определения местоположения отключены.',
    '位置服务已禁用。',
    '位置サービスは無効です。',
    'Lokalizacja wyłączona.',
    'Οι υπηρεσίες τοποθεσίας είναι απενεργοποιημένες.'
  ],
  'location permission is denied': [
    'location permission is denied',
    'A helyengedélyt megtagadták',
    'Se denegó el permiso de ubicación',
    "L'autorisation de localisation est refusée",
    'Standortberechtigung verweigert',
    'Permesso di posizione negato',
    'Permissão de localização negada',
    'Отказано в разрешении на местоположение',
    '位置权限已拒绝',
    '位置許可が拒否されました',
    'Odmowa pozwolenia na lokalizację',
    'Έχει απαγορευθεί η άδεια τοποθεσίας'
  ],
  'location permission denied forever': [
    'location permission denied forever',
    'A helyengedélyt örökre megtagadták',
    'Permiso de ubicación denegado para siempre',
    "Autorisation de localisation refusée définitivement",
    'Standortberechtigung für immer verweigert',
    'Permesso di posizione negato per sempre',
    'Permissão de localização negada para sempre',
    'Разрешение на местоположение отклонено навсегда',
    '位置权限已永久拒绝',
    '位置許可が永久に拒否されました',
    'Trwała odmowa pozwolenia na lokalizację',
    'Έχει απαγορευθεί η άδεια τοποθεσίας επ αόριστον'
  ],
  'failed to access gps': [
    'failed to access gps',
    'Nem sikerült hozzáférni a GPS-hez',
    'No se pudo acceder al GPS',
    "Impossible d'accéder au GPS",
    'GPS-Zugriff fehlgeschlagen',
    'Impossibile accedere al GPS',
    'Falha ao acessar o GPS',
    'Не удалось получить доступ к GPS',
    '无法访问 GPS',
    'GPSにアクセスできませんでした',
    'gps niedostępny',
    'Αποτυχία σύνδεσης στο GPS'
  ],
  'Search...': [
    'Search...',
    'Keresés...',
    'Buscar...',
    'Rechercher...',
    'Suchen...',
    'Cerca...',
    'Buscar...',
    'Поиск...',
    '搜索...',
    '検索...',
    'Szukam...',
    'Αναζήτηση...'
  ],
  'sunrise/sunset': [
    'sunrise/sunset',
    'napkelte/napnyugta',
    'amanecer/anochecer',
    'lever/coucher du soleil',
    'Sonnenaufgang/Sonnenuntergang',
    'alba/tramonto',
    'nascer do sol/pôr do sol',
    'восход/заход солнца',
    '日出/日落',
    '日の出/日没',
    'wschód/zachód',
    'ανατολή/δύση ηλίου'
  ],
  'air quality': [
    'air quality',
    'levegő minősége',
    'calidad del aire',
    'qualité de l\'air',
    'Luftqualität',
    'qualità dell\'aria',
    'qualidade do ar',
    'качество воздуха',
    '空气质量',
    '空気の質',
    'jakość powietrza',
    'ποιότητα αέρος'
  ],

  'good': [
    'good',
    'jó',
    'bueno',
    'bon',
    'gut',
    'buono',
    'bom',
    'хороший',
    '好',
    '良い',
    'dobry',
    'καλός'
  ],
  'fair': [
    'fair',
    'elfogadható',
    'aceptable',
    'passable',
    'akzeptabel',
    'accettabile',
    'razoável',
    'удовлетворительный',
    '公平',
    '公平',
    'dopuszczalny',
    'δίκαιος'
  ],
  'moderate': [
    'moderate',
    'mérsékelt',
    'moderado',
    'modéré',
    'mäßig',
    'moderato',
    'moderado',
    'умеренный',
    '适中',
    '適度',
    'umiarkowany',
    'μέτριος'
  ],
  'poor': [
    'poor',
    'gyenge',
    'pobre',
    'pauvre',
    'schlecht',
    'scarso',
    'pobre',
    'плохой',
    '较差',
    '悪い',
    'słaby',
    'κακός'
  ],
  'very poor': [
    'very poor',
    'nagyon gyenge',
    'muy pobre',
    'très pauvre',
    'sehr schlecht',
    'molto scarso',
    'muito pobre',
    'очень плохой',
    '非常差',
    '非常に悪い',
    'bardzo słaby',
    'πολύ κακός'
  ],
  'unhealthy': [
    'unhealthy',
    'egészségtelen',
    'insalubre',
    'malsain',
    'ungesund',
    'malsano',
    'insalubre',
    'вредный для здоровья',
    '不健康',
    '不健康',
    'niezdrowy',
    'ανθυγιεινός'
  ],

  'precipitation': [
    'precipitation',
    'csapadék',
    'precipitación',
    'précipitations',
    'Niederschlag',
    'precipitazione',
    'precipitação',
    'осадки',
    '降水',
    '降水',
    'opady',
    'βροχόπτωση'
  ],
  'radar': [
    'radar',
    'radar',
    'radar',
    'radar',
    'Radar',
    'radar',
    'radar',
    'радар',
    '雷达',
    'レーダー',
    'radar',
    'ραντάρ'
  ],
  'Color mode': [
    'Color mode',
    'Színmód',
    'Modo de color',
    'Mode couleur',
    'Farbmodus',
    'Modalità colore',
    'Modo de cor',
    'Режим цвета',
    '彩色模式',
    'カラーモード',
    'Schemat kolorów',
    'Λειτουργεία χρώματος'
  ],
  'Weather provider': [
    'Weather provider',
    'Időjárás szolgáltató',
    'Proveedor de clima',
    'Fournisseur de météo',
    'Wetteranbieter',
    'Fornitore di previsioni meteorologiche',
    'Provedor de clima',
    'Поставщик погоды',
    '天气服务提供商',
    '天気プロバイダ',
    'Dostawca pogody',
    'Πάροχος καιρού'
  ],
  'Time mode': [
    'Time mode',
    'Idő mód',
    'Modo de tiempo',
    'Mode temps',
    'Zeitmodus',
    'Modalità tempo',
    'Modo de tempo',
    'Режим времени',
    '时间模式',
    '時間モード',
    'Format czasu',
    'Μορφή ώρας'
  ],
  'Mon': [
    'Mon',
    'H',
    'Lun',
    'Lun',
    'Mo',
    'Lun',
    'Seg',
    'Пн',
    '一',
    '月',
    'Pon',
    'Δευ'
  ],
  'Tue': [
    'Tue',
    'K',
    'Mar',
    'Mar',
    'Di',
    'Mar',
    'Ter',
    'Вт',
    '二',
    '火',
    'Wt',
    'Τρι'
  ],
  'Wed': [
    'Wed',
    'Sz',
    'Mié',
    'Mer',
    'Mi',
    'Mer',
    'Qua',
    'Ср',
    '三',
    '水',
    'Śr',
    'Τετ'
  ],
  'Thu': [
    'Thu',
    'Cs',
    'Jue',
    'Jeu',
    'Do',
    'Gio',
    'Qui',
    'Чт',
    '四',
    '木',
    'Czw',
    'Πεμ'
  ],
  'Fri': [
    'Fri',
    'P',
    'Vie',
    'Ven',
    'Fr',
    'Ven',
    'Sex',
    'Пт',
    '五',
    '金',
    'Pt',
    'Παρ'
  ],
  'Sat': [
    'Sat',
    'Szo',
    'Sáb',
    'Sam',
    'Sa',
    'Sab',
    'Sáb',
    'Сб',
    '六',
    '土',
    'Sob',
    'Σαβ'
  ],
  'Sun': [
    'Sun',
    'V',
    'Dom',
    'Dim',
    'So',
    'Dom',
    'Dom',
    'Вс',
    '日',
    '日',
    'Nd',
    'Κυρ'
  ],
  'Font size': [
    'Font size',
    'Betűméret',
    'Tamaño de fuente',
    'Taille de police',
    'Schriftgröße',
    'Carattere',
    'Tamanho da fonte',
    'Размер шрифта',
    '字体大小',
    'フォントサイズ',
    'Rozmiar czcionki',
    'Μέγεθος γραμματοσειράς'
  ],
  'Error Screen': [
    'Error Screen',
    'Hiba képernyő',
    'Pantalla de error',
    'Écran d erreur',
    'Fehlerbildschirm',
    'Schermata di errore',
    'Tela de erro',
    'Экран ошибки',
    '错误屏幕',
    'エラースクリーン',
    'Ekran błędu',
    'Οθόνη Σφάλματος'

  ],
  'Daily': [
    'Daily',
    'Napi',
    'Diario',
    'Quotidien',
    'Täglich',
    'Giornaliero',
    'Diário',
    'Ежедневно',
    '每日',
    'デイリー',
    'Nastepne dni',
    'Καθημερινά'
  ],
  'Search provider': [
    'Search provider',
    'Keresési szolgáltató',
    'Proveedor de búsqueda',
    'Fournisseur de recherche',
    'Suchanbieter',
    'Provider di ricerca',
    'Provedor de pesquisa',
    'Поставщик поиска',
    '搜索提供商',
    '検索プロバイダー',
    'Dostawca wyszukiwania',
    'Πάροχος αναζήτησης'
  ],
  'updated, x min ago': [
    'updated, x min ago',
    'frissítve, x percel ezelőtt',
    'actualizado, x min hace',
    'mis à jour, il y a x min',
    'aktualisiert, vor x min',
    'aggiornato, x min fa',
    'atualizado, x min atrás',
    'обновлено, x мин назад',
    '更新于 x 分钟前',
    'x 分前に更新されました',
    'zaktualizowane, x min temu',
    'ανανεώθηκε, x λεπτά πρίν'
  ],
  'updated, just now': [
    'updated, just now',
    'frissítve, épp most',
    'actualizado, justo ahora',
    'mis à jour, juste maintenant',
    'aktualisiert, gerade jetzt',
    'aggiornato, proprio adesso',
    'atualizado, agora mesmo',
    'обновлено, прямо сейчас',
    '刚刚更新',
    'ちょうど今更新',
    'zaktualizowane, właśnie teraz',
    'ανανεώθηκε, μόλις τώρα'
  ],

  'Color source': [
    'Color source',
    'Szín forrása',
    'Fuente de color',
    'Source de couleur',
    'Farbquelle',
    'Fonte di colore',
    'Fonte de cor',
    'Источник цвета',
    '颜色来源',
    'カラーソース',
    'Źródło koloru',
    'Πηγή χρώματος'
  ],
  'Image source': [
    'Image source',
    'Kép forrása',
    'Fuente de imagen',
    "Source d'image",
    'Bildquelle',
    "Fonte dell'immagine",
    'Fonte de imagem',
    'Источник изображения',
    '图片来源',
    '画像ソース',
    'Źródło obrazu',
    'Πηγή εικόνας'
  ],

  'temp': [
    'temp',
    'hőmérs.',
    'temp',
    'temp',
    'temp',
    'temp',
    'temp',
    'темп',
    '温度',
    '気温',
    'temp',
    'θερμ.'
  ],
  'precip': [
    'precip',
    'csapad.',
    'precip',
    'précip',
    'Niederschl.',
    'precip',
    'precip',
    'осадки',
    '降水',
    '降水',
    'opad',
    'κατ. βροχής'
  ],
  'wind': [
    'wind',
    'szél',
    'viento',
    'vent',
    'wind',
    'vento',
    'vento',
    'ветер',
    '风',
    '風',
    'wiatr',
    'άνεμος'
  ],
  'uv': [
    'uv',
    'uv',
    'uv',
    'uv',
    'uv',
    'uv',
    'uv',
    'ув',
    '紫外线',
    '紫外線',
    'uv',
    'uv'
  ],

  'Air quality is excellent; no health risk.': [
    'Air quality is excellent; no health risk.',
    'A levegő minősége kiváló; nincs egészségügyi kockázat.',
    'La calidad del aire es excelente; no hay riesgo para la salud.',
    "La qualité de l'air est excellente; aucun risque pour la santé.",
    'Die Luftqualität ist ausgezeichnet; kein Gesundheitsrisiko.',
    "La qualità dell'aria è eccellente; nessun rischio per la salute.",
    'A qualidade do ar é excelente; sem risco à saúde.',
    'Качество воздуха отличное; угрозы для здоровья нет.',
    '空气质量极佳；无健康风险。',
    '空気の質は非常に良好です。健康へのリスクはありません。',
    'Jakość powietrza jest doskonała; brak ryzyka dla zdrowia.',
    'Η ποιότητα του αέρα είναι εξαιρετική. Δεν υπάρχει κίνδυνος για την υγεία.'
  ],
  'Acceptable air quality; minor risk for sensitive people.': [
    'Acceptable air quality; minor risk for sensitive people.',
    'Elfogadható a levegő minősége; kisebb kockázat az érzékeny emberek számára.',
    'Calidad del aire aceptable; riesgo menor para personas sensibles.',
    "Qualité de l'air acceptable; risque mineur pour les personnes sensibles.",
    'Akzeptable Luftqualität; geringes Risiko für empfindliche Personen.',
    "Qualità dell'aria accettabile; rischio minore per le persone sensibili.",
    'Qualidade do ar aceitável; risco menor para pessoas sensíveis.',
    'Приемлемое качество воздуха; незначительный риск для чувствительных людей.',
    '可接受的空气质量；对敏感人群有轻微风险。',
    '許容できる空気の質。敏感な人にわずかなリスクがあります。',
    'Akceptowalna jakość powietrza; niewielkie ryzyko dla osób wrażliwych.',
    'Αποδεκτή ποιότητα αέρα· ελάχιστος κίνδυνος για ευαίσθητα άτομα.'
  ],
  'Sensitive individuals may experience mild effects.': [
    'Sensitive individuals may experience mild effects.',
    'Az érzékeny egyének enyhe hatásokat tapasztalhatnak.',
    'Las personas sensibles pueden experimentar efectos leves.',
    'Les personnes sensibles peuvent ressentir des effets légers.',
    'Empfindliche Personen können leichte Auswirkungen erfahren.',
    'Gli individui sensibili possono sperimentare effetti lievi.',
    'Indivíduos sensíveis podem sentir efeitos leves.',
    'Чувствительные люди могут испытывать легкие эффекты.',
    '敏感人群可能会出现轻微影响。',
    '敏感な人々は軽度の影響を受ける可能性があります。',
    'Osoby wrażliwe mogą odczuwać łagodne skutki.',
    'Τα ευαίσθητα άτομα ενδέχεται να παρουσιάσουν ήπια αποτελέσματα.'
  ],
  'Health effects possible for everyone, serious for sensitive groups.': [
    'Health effects possible for everyone, serious for sensitive groups.',
    'Egészségügyi hatások mindenkire, súlyos hatások az érzékeny csoportokra.',
    'Posibles efectos en la salud para todos, graves para grupos sensibles.',
    'Effets sur la santé possibles pour tout le monde, graves pour les groupes sensibles.',
    'Gesundheitliche Auswirkungen möglich für alle, ernst für empfindliche Gruppen.',
    'Effetti sulla salute possibili per tutti, seri per i gruppi sensibili.',
    'Efeitos na saúde possíveis para todos, sérios para grupos sensíveis.',
    'Возможны последствия для здоровья у всех, серьезные для чувствительных групп.',
    '可能对所有人造成健康影响，对敏感人群影响严重。',
    'すべての人に健康への影響があり、敏感なグループにとって深刻です。',
    'Możliwe skutki zdrowotne dla wszystkich, poważne dla grup wrażliwych.',
    'Πιθανές επιπτώσεις στην υγεία για όλους, σοβαρές για τις ευαίσθητες ομάδες.'
  ],
  'Serious health effects for everyone.': [
    'Serious health effects for everyone.',
    'Súlyos egészségügyi hatások mindenkire.',
    'Graves efectos en la salud para todos.',
    'Effets graves sur la santé pour tout le monde.',
    'Schwere gesundheitliche Auswirkungen für alle.',
    'Effetti gravi sulla salute per tutti.',
    'Graves efeitos na saúde para todos.',
    'Серьезные последствия для здоровья у всех.',
    '对所有人都有严重的健康影响。',
    'すべての人に深刻な健康への影響があります。',
    'Poważne skutki zdrowotne dla wszystkich.',
    'Σοβαρές επιπτώσεις στην υγεία για όλους.'
  ],
  'Emergency conditions; severe health effects for all.': [
    'Emergency conditions; severe health effects for all.',
    'Vészhelyzet; súlyos egészségügyi hatások mindenkire.',
    'Condiciones de emergencia; graves efectos en la salud para todos.',
    "Conditions d'urgence; effets graves sur la santé pour tout le monde.",
    'Notfallbedingungen; schwere gesundheitliche Auswirkungen für alle.',
    'Condizioni di emergenza; gravi effetti sulla salute per tutti.',
    'Condições de emergência; graves efeitos na saúde para todos.',
    'Чрезвычайные условия; серьезные последствия для здоровья у всех.',
    '紧急情况；对所有人造成严重的健康影响。',
    '緊急事態。すべての人に深刻な健康への影響があります。',
    'Warunki awaryjne; poważne skutki zdrowotne dla wszystkich.',
    'Συνθήκες έκτακτης ανάγκης· σοβαρές επιπτώσεις στην υγεία για όλους.'
  ],

  'photo by x on Unsplash': [ //commas are added to separate the clickable text (photo, name, Unsplash)
    'Photo, by ,x, on ,Unsplash', //from the non clickable ones (by, on)
    'Fotó,: ,x, az ,Unsplashen',
    'Foto, de ,x, en ,Unsplash',
    'Photo, de ,x, sur ,Unsplash',
    'Foto, von ,x, auf ,Unsplash',
    'Foto, di ,x, su ,Unsplash',
    'Foto, de ,x, no ,Unsplash',
    'Фото, ,x, на ,Unsplash',
    '照片, ,x, 拍摄，发布于 ,Unsplash',
    '写真,: ,x, on ,Unsplash',
    'Zdjęcie, ,x, na ,Unsplash',
    'Φωτογραφία, από τον ,x, στο ,Unsplash'
  ],

  'developed by:': [
    'Developed by:',
    'Fejlesztette:',
    'Desarrollado por:',
    'Développé par :',
    'Entwickelt von:',
    'Sviluppato da:',
    'Desenvolvido por:',
    'Разработано:',
    '开发者：',
    '開発者：',
    'Opracowane przez:',
    'Αναπτύχθηκε από:',
  ],
  'source code': [
    'Source code',
    'Forráskód',
    'Código fuente',
    'Code source',
    'Quellcode',
    'Codice sorgente',
    'Código-fonte',
    'Исходный код',
    '源代码',
    'ソースコード',
    'Kod źródłowy',
    'Πηγαίος κώδικας',
  ],
  'report an issue': [
    'Report an issue',
    'Hiba jelentése',
    'Informar de un problema',
    'Signaler un problème',
    'Ein Problem melden',
    'Segnala un problema',
    'Relatar um problema',
    'Сообщить о проблеме',
    '报告问题',
    '問題を報告する',
    'Zgłoś problem',
    'Αναφορά προβλήματος',
  ],
  'weather data:': [
    'Weather data:',
    'Időjárási adatok:',
    'Datos meteorológicos:',
    'Données météorologiques :',
    'Wetterdaten:',
    'Dati meteorologici:',
    'Dados meteorológicos:',
    'Метеоданные:',
    '天气数据：',
    '気象データ：',
    'Dane pogodowe:',
    'Δεδομένα καιρού:',
  ],
  'all images used are from:': [
    'All images used are from:',
    'Minden felhasznált kép forrása:',
    'Todas las imágenes utilizadas son de:',
    'Toutes les images utilisées proviennent de :',
    'Alle verwendeten Bilder stammen von:',
    'Tutte le immagini utilizzate provengono da:',
    'Todas as imagens usadas são de:',
    'Все использованные изображения из:',
    '所有使用的图片来自：',
    '使用されているすべての画像は次の提供です：',
    'Wszystkie użyte obrazy pochodzą z:',
    'Όλες οι εικόνες που χρησιμοποιούνται είναι από:',
  ],
  'Overmorrow donate text': [
    'Overmorrow was always meant to be a totally free app, without any ads or in-app-purchases. \n \nSo if you just want to use it like that then please do enjoy. \n \nIf however you like using it and you feel like it\'s worth \$1 of your money then please consider supporting the project on my Patreon.',
    'Overmorrow mindig is teljesen ingyenes alkalmazásnak készült, hirdetések és alkalmazáson belüli vásárlások nélkül. \n \nHa csak így szeretnéd használni, akkor élvezd bátran. \n \nHa azonban szereted használni, és úgy érzed, hogy megér egy dollárt, kérlek, fontold meg a projekt támogatását a Patreonomon.',
    'Overmorrow siempre estuvo destinado a ser una aplicación completamente gratuita, sin anuncios ni compras dentro de la aplicación. \n \nAsí que si solo quieres usarla así, disfrútala. \n \nSin embargo, si te gusta usarla y sientes que vale un dólar de tu dinero, considera apoyar el proyecto en mi Patreon.',
    'Overmorrow a toujours été conçu pour être une application totalement gratuite, sans aucune publicité ni achats intégrés. \n \nDonc si vous voulez juste l\'utiliser comme ça, profitez-en. \n \nCependant, si vous aimez l\'utiliser et que vous pensez que cela vaut un dollar, envisagez de soutenir le projet sur mon Patreon.',
    'Overmorrow war immer als völlig kostenlose App gedacht, ohne Werbung oder In-App-Käufe. \n \nWenn du sie also einfach so nutzen möchtest, dann genieße es. \n \nWenn dir die Nutzung gefällt und du denkst, dass sie einen Dollar wert ist, erwäge bitte, das Projekt auf meinem Patreon zu unterstützen.',
    'Overmorrow è sempre stata pensata come un\'app completamente gratuita, senza pubblicità o acquisti in-app. \n \nQuindi, se vuoi usarla così, per favore, goditela. \n \nTuttavia, se ti piace usarla e pensi che valga un dollaro, considera di supportare il progetto su Patreon.',
    'Overmorrow sempre foi planejado para ser um aplicativo totalmente gratuito, sem anúncios ou compras dentro do app. \n \nEntão, se você quiser apenas usá-lo assim, aproveite. \n \nNo entanto, se você gosta de usá-lo e sente que vale um dólar, considere apoiar o projeto no meu Patreon.',
    'Overmorrow всегда задумывался как полностью бесплатное приложение, без рекламы и встроенных покупок. \n \nЕсли вы хотите просто пользоваться им таким образом, пожалуйста, наслаждайтесь. \n \nЕсли вам нравится пользоваться приложением, и вы считаете, что оно стоит одного доллара, пожалуйста, подумайте о поддержке проекта на моем Patreon.',
    'Overmorrow 始终是一款完全免费的应用程序，没有任何广告或应用内购买。\n \n所以如果您只想这样使用它，那么请尽情享用。\n \n但是，如果您喜欢使用它，并觉得它值 1 美元，请考虑在我的 Patreon 上支持该项目。',
    'Overmorrow は、広告やアプリ内購入がない完全無料のアプリとして常に意図されていました。\n \nそれだけで使いたい場合は、ぜひお楽しみください。\n \nただし、気に入っていただけて、それが 1 ドルの価値があると感じた場合は、私の Patreon でプロジェクトをサポートすることをご検討ください。',
    'Overmorrow zawsze miało być całkowicie darmową aplikacją, bez żadnych reklam ani zakupów w aplikacji.\n \nWięc jeśli chcesz jej tak używać, proszę bardzo.\n \nJeśli jednak lubisz ją używać i uważasz, że jest warta dolara, rozważ wsparcie projektu na moim Patreon.',
    'Το Overmorrow προοριζόταν πάντα να είναι μια εντελώς δωρεάν εφαρμογή, χωρίς διαφημίσεις ή αγορές εντός εφαρμογής. \n \nΑν λοιπόν θέλετε να το χρησιμοποιήσετε έτσι, απολαύστε το. \n \nΩστόσο, εάν σας αρέσει να το χρησιμοποιείτε και αισθάνεστε ότι αξίζει 1 δολάριο από τα χρήματά σας, σκεφτείτε να στηρίξετε το έργο στο Patreon μου.'
  ],
  'Support on Patreon': [
    'Support on Patreon',
    'Támogatás a Patreonon',
    'Apoyo en Patreon',
    'Soutien sur Patreon',
    'Unterstützung auf Patreon',
    'Supporto su Patreon',
    'Apoio no Patreon',
    'Поддержка на Patreon',
    '在 Patreon 上支持',
    'Patreon でサポート',
    'Wsparcie na Patreon',
    'Υποστήριξη στο Patreon'
  ],

  'rain expected in the next half an hour': [
    'rain expected in the next half an hour',
    'eső várható a következő fél órában',
    'se espera lluvia en la próxima media hora',
    'pluie attendue dans la prochaine demi-heure',
    'regen in der nächsten halben Stunde erwartet',
    'pioggia prevista nella prossima mezz\'ora',
    'chuva esperada na próxima meia hora',
    'ожидается дождь в течение следующего получаса',
    '预计在接下来的半小时内下雨',
    '雨が次の30分以内に予想されます',
    'deszcz spodziewany w ciągu następnych pół godziny',
    'αναμένεται βροχή στο επόμενο μισάωρο'
  ],
  'rain expected in the next x minutes': [
    'rain expected in the next x minutes',
    'eső várható a következő x percben',
    'se espera lluvia en los próximos x minutos',
    'pluie attendue dans les x prochaines minutes',
    'regen in den nächsten x Minuten erwartet',
    'pioggia prevista nei prossimi x minuti',
    'chuva esperada nos próximos x minutos',
    'ожидается дождь в течение следующих x минут',
    '预计在接下来的 x 分钟内下雨',
    '雨が次の x 分以内に予想されます',
    'deszcz spodziewany w ciągu następnych x minut',
    'αναμένεται βροχή στα επόμενα x λεπτά'
  ],
  'rain expected in the next 1 hour': [
    'rain expected in the next 1 hour',
    'eső várható a következő 1 órában',
    'se espera lluvia en la próxima 1 hora',
    'pluie attendue dans la prochaine heure',
    'regen in der nächsten Stunde erwartet',
    'pioggia prevista nell\'ora successiva',
    'chuva esperada na próxima 1 hora',
    'ожидается дождь в течение следующего часа',
    '预计在接下来的 1 小时内下雨',
    '雨が次の1時間以内に予想されます',
    'deszcz spodziewany w ciągu następnej godziny',
    'αναμένεται βροχή στην επόμενη 1 ώρα'
  ],
  'rain expected in the next x hours': [
    'rain expected in the next x hours',
    'eső várható a következő x órában',
    'se espera lluvia en las próximas x horas',
    'pluie attendue dans les x prochaines heures',
    'regen in den nächsten x Stunden erwartet',
    'pioggia prevista nelle prossime x ore',
    'chuva esperada nas próximas x horas',
    'ожидается дождь в течение следующих x часов',
    '预计在接下来的 x 小时内下雨',
    '雨が次の x 時間以内に予想されます',
    'deszcz spodziewany w ciągu następnych x godzin',
    'αναμένεται βροχή στις επόμενες x ώρες'
  ],
  'rain expected in x minutes': [
    'rain expected in x minutes',
    'eső várható x perc múlva',
    'se espera lluvia en x minutos',
    'pluie attendue dans x minutes',
    'regen in x Minuten erwartet',
    'pioggia prevista tra x minuti',
    'chuva esperada em x minutos',
    'ожидается дождь через x минут',
    '预计在 x 分钟内下雨',
    '雨が x 分以内に予想されます',
    'deszcz spodziewany za x minut',
    'αναμένεται βροχή σε x λεπτά'
  ],
  'rain expected in 1 hour': [
    'rain expected in 1 hour',
    'eső várható 1 óra múlva',
    'se espera lluvia en 1 hora',
    'pluie attendue dans 1 heure',
    'regen in 1 Stunde erwartet',
    'pioggia prevista tra 1 ora',
    'chuva esperada em 1 hora',
    'ожидается дождь через 1 час',
    '预计在 1 小时内下雨',
    '雨が1時間以内に予想されます',
    'deszcz spodziewany za 1 godzinę',
    'αναμένεται βροχή σε 1 ώρα'
  ],
  'rain expected in x hours': [
    'rain expected in x hours',
    'eső várható x óra múlva',
    'se espera lluvia en x horas',
    'pluie attendue dans x heures',
    'regen in x Stunden erwartet',
    'pioggia prevista tra x ore',
    'chuva esperada em x horas',
    'ожидается дождь через x часов',
    '预计在 x 小时内下雨',
    '雨が x 時間以内に予想されます',
    'deszcz spodziewany za x godzin',
    'αναμένεται βροχή σε x ώρες'
  ],

  'Appearance': [
    'Appearance',
    'Megjelenés',
    'Apariencia',
    'Apparence',
    'Erscheinungsbild',
    'Aspetto',
    'Aparência',
    'Внешний вид',
    '外观',
    '外観',
    'Wygląd',
    'Εμφάνιση'
  ],
  'General': [
    'General',
    'Általános',
    'General',
    'Général',
    'Allgemein',
    'Generale',
    'Geral',
    'Общие',
    '常规',
    '一般',
    'Ogólne',
    'Γενικά'
  ],
  'Units': [
    'Units',
    'Egységek',
    'Unidades',
    'Unités',
    'Einheiten',
    'Unità',
    'Unidades',
    'Единицы',
    '单位',
    '単位',
    'Jednostki',
    'Μονάδες'
  ],

  "color theme, image source": [
    'color theme, image source',
    'színtéma, kép forrása',
    'tema de color, fuente de imagen',
    'thème de couleur, source d\'image',
    'Farbschema, Bildquelle',
    'tema colore, sorgente immagine',
    'tema de cor, fonte de imagem',
    'цветовая тема, источник изображения',
    '颜色主题, 图片来源',
    'カラーテーマ, 画像のソース',
    'motyw kolorystyczny, źródło obrazu',
    'θέμα χρωμάτων, πηγή εικόνας'
  ],
  "time mode, font size": [
    'time mode, font size',
    'idő mód, betűméret',
    'modo de tiempo, tamaño de fuente',
    'mode de temps, taille de police',
    'Zeitmodus, Schriftgröße',
    'modalità tempo, dimensione del carattere',
    'modo de tempo, tamanho da fonte',
    'режим времени, размер шрифта',
    '时间模式, 字体大小',
    '時間モード, フォントサイズ',
    'tryb czasu, rozmiar czcionki',
    'λειτουργία χρόνου, μέγεθος γραμματοσειράς'
  ],
  "the language used": [
    'the language used',
    'használt nyelv',
    'el idioma utilizado',
    'la langue utilisée',
    'die verwendete Sprache',
    'la lingua utilizzata',
    'o idioma usado',
    'используемый язык',
    '使用的语言',
    '使用されている言語',
    'używany język',
    'η χρησιμοποιούμενη γλώσσα'
  ],
  "the units used in the app": [
    'the units used in the app',
    'az alkalmazásban használt egységek',
    'las unidades utilizadas en la aplicación',
    'les unités utilisées dans l\'application',
    'die in der App verwendeten Einheiten',
    'le unità utilizzate nell\'app',
    'as unidades usadas no aplicativo',
    'единицы, используемые в приложении',
    '应用中使用的单位',
    'アプリで使用される単位',
    'jednostki używane w aplikacji',
    'οι μονάδες που χρησιμοποιούνται στην εφαρμογή'
  ],
  "now": [
    'now',
    'most',
    'ahora',
    'maintenant',
    'jetzt',
    'ora',
    'agora',
    'сейчас',
    '现在',
    '今',
    'teraz',
    'τώρα'
  ],
  "hr": [
    'hr',
    'ó',
    'h',
    'h',
    'Std',
    'h',
    'h',
    'ч',
    '小时',
    '時',
    'godz.',
    'ώ',
  ],

  "Overmorrow 2.4.0 introduces Network images!": [
    'Overmorrow 2.4.0 introduces Network images!',
    'Az Overmorrow 2.4.0 hálózati képeket vezet be!',
    '¡Overmorrow 2.4.0 introduce imágenes de red!',
    'Overmorrow 2.4.0 introduit des images réseau !',
    'Overmorrow 2.4.0 führt Netzwerkbilder ein!',
    'Overmorrow 2.4.0 introduce immagini di rete!',
    'Overmorrow 2.4.0 introduz imagens de rede!',
    'Overmorrow 2.4.0 представляет сетевые изображения!',
    'Overmorrow 2.4.0 引入了网络图像！',
    'Overmorrow 2.4.0 にネットワーク画像を導入！',
    'Overmorrow 2.4.0 wprowadza obrazy z sieci!',
    'Το Overmorrow 2.4.0 εισάγει εικόνες δικτύου!'
  ],
  "Would you like to enable network images?": [
    'Would you like to enable network images?',
    'Szeretnéd engedélyezni a hálózati képeket?',
    '¿Te gustaría habilitar imágenes de red?',
    'Souhaitez-vous activer les images réseau ?',
    'Möchten Sie Netzwerkbilder aktivieren?',
    'Vuoi abilitare le immagini di rete?',
    'Gostaria de ativar as imagens de rede?',
    'Хотите включить сетевые изображения?',
    '您想启用网络图像吗？',
    'ネットワーク画像を有効にしますか？',
    'Czy chcesz włączyć obrazy z sieci?',
    'Θέλετε να ενεργοποιήσετε τις εικόνες δικτύου;'
  ],
  "note: you can always change later by going into settings > appearance > image source": [
    'note: you can always change later by going into settings > appearance > image source',
    'megjegyzés: később bármikor módosíthatja a beállítások > megjelenés > kép forrása menüpontban',
    'nota: siempre puedes cambiarlo más tarde en configuración > apariencia > fuente de imagen',
    'remarque : vous pouvez toujours modifier plus tard en allant dans paramètres > apparence > source d\'image',
    'Hinweis: Sie können dies später jederzeit unter Einstellungen > Erscheinungsbild > Bildquelle ändern',
    'nota: puoi sempre modificarlo in seguito andando su impostazioni > aspetto > sorgente immagine',
    'nota: você pode sempre mudar depois indo para configurações > aparência > fonte de imagem',
    'примечание: вы всегда можете изменить это позже в настройках > внешний вид > источник изображения',
    '注意：您可以随时通过进入设置 > 外观 > 图片来源来更改',
    '注意：設定 > 外観 > 画像のソース で後からいつでも変更できます',
    'uwaga: zawsze możesz to zmienić później, przechodząc do ustawień > wygląd > źródło obrazu',
    'σημείωση: μπορείτε πάντα να αλλάξετε αργότερα πηγαίνοντας στις ρυθμίσεις > εμφάνιση > πηγή εικόνας'
  ],
  "Disable": [
    'Disable',
    'Letiltás',
    'Desactivar',
    'Désactiver',
    'Deaktivieren',
    'Disabilita',
    'Desativar',
    'Отключить',
    '禁用',
    '無効化',
    'Wyłącz',
    'Απενεργοποίηση'
  ],
  "Enable": [
    'Enable',
    'Engedélyezés',
    'Habilitar',
    'Activer',
    'Aktivieren',
    'Abilita',
    'Ativar',
    'Включить',
    '启用',
    '有効化',
    'Włącz',
    'Ενεργοποίηση'
  ],
  "Layout": [
    'Layout',
    'Elrendezés',
    'Diseño',
    'Disposition',
    'Layout',
    'Layout',
    'Layout',
    'Макет',
    '布局',
    'レイアウト',
    'Układ',
    'Διάταξη'
  ],
  "widget order, customization": [
    'widget order, customization',
    'widget sorrend, személyreszabás',
    'orden de widgets, personalización',
    'ordre des widgets, personnalisation',
    'Widget-Reihenfolge, Anpassung',
    'ordine dei widget, personalizzazione',
    'ordem de widgets, personalização',
    'порядок виджетов, настройка',
    '小部件顺序，自定义',
    'ウィジェットの順序、カスタマイズ',
    'kolejność widżetów, dostosowanie',
    'σειρά widget, προσαρμογή'
  ],
  "30m": [
    '30m',
    '30p',
    '30m',
    '30m',
    '30m',
    '30m',
    '30m',
    '30м',
    '30分',
    '30分',
    '30m',
    '30λ',
  ],

  'Search translation': [ //used for getting the codes used for translation of city names
                          //If none are available then en (english) is the default
                          // for more info visit https://open-meteo.com/en/docs/geocoding-api
    'en',
    'en',
    'sp',
    'fr',
    'de',
    'it',
    'pt',
    'ru',
    'en',
    'en',
    'en',
    'en'
  ]
};


