Map<String, int> languageIndex = {
  'English' : 0,
  'Magyar' : 1,
  'Español' : 2,
  'Français' : 3,
  'Deutsch' : 4,
  'Italiano' : 5,
  'Português' : 6,
  'Русский' : 7,
  '简体中文' : 8,
  '日本語' : 9,
};

Map<String, List<String>> mainTranslate = {
  'temp. max': [
    'Max. Temp',
    'Max. hőmérséklet',
    'Temp. Máxima',
    'Temp. Maximale',
    'Max. Temperatur',
    'Temp. Massima',
    'Temp. Máxima',
    'Максимальная температура',
    '最高温度',
    '最高気温'
  ],
  'temp. min': [
    'Min. Temp',
    'Min. hőmérséklet',
    'Temp. Mínima',
    'Temp. Minimale',
    'Min. Temperatur',
    'Temp. Minima',
    'Temp. Mínima',
    'Минимальная температура',
    '最低温度',
    '最低気温'
  ],
  'precip.': [
    'Precip.',
    'Csapadék',
    'Precip.',
    'Précip.',
    'Niederschlag',
    'Precipitazione',
    'Precip.',
    'Осадки',
    '降水',
    '降水量'
  ],
  'Settings': [
    'Settings',
    'Beállítások',
    'Configuración',
    'Paramètres',
    'Einstellungen',
    'Impostazioni',
    'Configurações',
    'Настройки',
    '设置',
    '設定'
  ],
  'Donate': [
    'Donate',
    'Adományozás',
    'Donar',
    'Donner',
    'Spenden',
    'Dona',
    'Doar',
    'Пожертвовать',
    '捐赠',
    '寄付'
  ],
  'About': [
    'About',
    'Névjegy',
    'Acerca de',
    'À propos de',
    'Über',
    'Informazioni',
    'Sobre',
    'О программе',
    '关于',
    '紹介'
  ],
  'Wind': [
    'Wind',
    'Szél',
    'Viento',
    'Vent',
    'Wind',
    'Vento',
    'Vento',
    'Ветер',
    '风',
    '風'
  ],
  'Today': [
    'Today',
    'Ma',
    'Hoy',
    'Aujourd hui',
    'Heute',
    'Oggi',
    'Hoje',
    'Сегодня',
    '今天',
    '今日'
  ],
  'Tomorrow': [
    'Tomorrow',
    'Holnap',
    'Mañana',
    'Demain',
    'Morgen',
    'Domani',
    'Amanhã',
    'Завтра',
    '明天',
    '明日'
  ],
  'Overmorrow': [
    'Overmorrow',
    'Holnapután',
    'Pasado Mañana',
    'Après-demain',
    'Übermorgen',
    'Dopodomani',
    'Depois de Amanhã',
    'Послезавтра',
    '后天',
    '明後日'
  ],
  'Language': [
    'Language',
    'Nyelv',
    'Idioma',
    'Langue',
    'Sprache',
    'Lingua',
    'Língua',
    'Язык',
    '语言',
    '言語'
  ],
  'Temperature': [
    'Temp.',
    'Hőmérséklet',
    'Temperatura',
    'Température',
    'Temperatur',
    'Temperatura',
    'Temperatura',
    'Температура',
    '温度',
    '気温'
  ],
  'Rain': [
    'Rain',
    'Eső',
    'Lluvia',
    'Pluie',
    'Regen',
    'Pioggia',
    'Chuva',
    'Дождь',
    '雨',
    '雨'
  ],
  'Pressure': [
    'Pressure',
    'Nyomás',
    'Presión',
    'Pression',
    'Druck',
    'Pressione',
    'Pressão',
    'Давление',
    '压力',
    '圧力'
  ],
  'Favorites': [
    'Favorites',
    'Kedvencek',
    'Favoritos',
    'Favoris',
    'Favoriten',
    'Preferiti',
    'Favoritos',
    'Избранное',
    'お気に入り',
    'Favoritos'
  ],
  'Clear Night': [
    'Clear Night',
    'Tiszta éjszaka',
    'Noche despejada',
    'Nuit claire',
    'Klare Nacht',
    'Notte serena',
    'Noite limpa',
    'Чистая ночь',
    '晴朗的夜晚',
    '快晴の夜'
  ],
  'Partly Cloudy': [
    'Partly Cloudy',
    'Részben felhős',
    'Parcialmente nublado',
    'Partiellement nuageux',
    'Teils wolkig',
    'Parzialmente nuvoloso',
    'Parcialmente nublado',
    'Частичная облачность',
    '局部多云',
    '一部曇り'
  ],
  'Clear Sky': [
    'Clear Sky',
    'Tiszta ég',
    'Cielo despejado',
    'Ciel clair',
    'Klarer Himmel',
    'Cielo sereno',
    'Céu limpo',
    'Чистое небо',
    '晴朗的天空',
    '快晴'
  ],
  'Overcast': [
    'Overcast',
    'Borult',
    'Nublado',
    'Couvert',
    'Bedeckt',
    'Coperto',
    'Nublado',
    'Пасмурно',
    '阴天',
    '曇り'
  ],
  'Haze': [
    'Haze',
    'Köd',
    'Niebla',
    'Brume',
    'Dunst',
    'Foschia',
    'Neblina',
    'Туман',
    '雾霾',
    '霧'
  ],
  'Sleet': [
    'Sleet',
    'Hószitálás',
    'Aguanieve',
    'Neige fondue',
    'Schneeregen',
    'Pioggia congelata',
    'Chuva congelada',
    'Мокрый снег',
    '雨夹雪',
    'みぞれ'
  ],
  'Drizzle': [
    'Drizzle',
    'Szemerkél',
    'Llovizna',
    'Bruine',
    'Nieselregen',
    'Pioggerella',
    'Chuvisco',
    'Морось',
    '毛毛雨',
    '霧雨'
  ],
  'Thunderstorm': [
    'Thunderstorm',
    'Zivatar',
    'Tormenta',
    'Orage',
    'Gewitter',
    'Temporale',
    'Tempestade',
    'Гроза',
    '雷暴',
    '雷雨'
  ],
  'Heavy Snow': [
    'Heavy Snow',
    'Hóvihar',
    'Nevada intensa',
    'Forte neige',
    'Starker Schneefall',
    'Forte nevicata',
    'Neve intensa',
    'Сильный снег',
    '大雪',
    '大雪'
  ],
  'Fog': [
    'Fog',
    'Köd',
    'Nebbia',
    'Brouillard',
    'Nebel',
    'Nebbia',
    'Nevoeiro',
    'Туман',
    '雾',
    '霧'
  ],
  'Snow': [
    'Snow',
    'Hó',
    'Nieve',
    'Neige',
    'Schnee',
    'Neve',
    'Neve',
    'Снег',
    '雪',
    '雪'
  ],
  'Heavy Rain': [
    'Heavy Rain',
    'Erős eső',
    'Lluvia intensa',
    'Pluie forte',
    'Starker Regen',
    'Pioggia intensa',
    'Chuva intensa',
    'Сильный дождь',
    '大雨',
    '大雨'
  ],
  'Cloudy Night': [
    'Cloudy Night',
    'Felhős éjszaka',
    'Noche nublada',
    'Nuit nuageuse',
    'Bewölkte Nacht',
    'Notte nuvolosa',
    'Noite nublada',
    'Облачная ночь',
    '多云的夜晚',
    '多云の夜'
  ],
  'Overmorrow is a free app. :)': [
    'Overmorrow is a free app. :)',
    'Overmorrow egy ingyenes alkalmazás. :)',
    'Overmorrow es una aplicación gratuita. :)',
    'Overmorrow est une application gratuite. :)',
    'Overmorrow ist eine kostenlose App. :)',
    'Overmorrow è un app gratuita. :)',
    'O Overmorrow é um aplicativo gratuito. :)',
    'Overmorrow - бесплатное приложение. :)',
    'Overmorrow是一款免费应用程序。:)',
    'Overmorrowは無料のアプリです。:)'
  ],
  'Support me on Patreon, to help me keep it that way!': [
  'Support me on Patreon, to help me keep it that way!',
  'Támogass a Patreonon, hogy segíts nekem fenntartani! :)',
  '¡Apóyame en Patreon para ayudarme a mantenerlo así! :)',
  'Soutenez-moi sur Patreon pour m aider à le maintenir de cette manière ! :)',
  'Unterstützen Sie mich auf Patreon, um mir dabei zu helfen, es so zu halten! :)',
  'Sostienimi su Patreon per aiutarmi a mantenerlo in questo modo! :)',
  'Apoie-me no Patreon para me ajudar a mantê-lo assim! :)',
  'Поддержите меня на Patreon, чтобы помочь мне сохранить это так! :)',
  '在Patreon上支持我，以帮助我保持这种方式！:)',
  'これを維持するのを助けるためにPatreonで私をサポートしてください！:)'
  ],
  'Thank You! -Balint': [
    'Thank You! -Balint',
    'Köszönöm! -Balint',
    '¡Gracias! -Balint',
    'Merci ! -Balint',
    'Vielen Dank! -Balint',
    'Grazie! -Balint',
    'Obrigado! -Balint',
    'Спасибо! -Балинт',
    '谢谢！ -巴林特',
    'ありがとうございます！ -バリント'
  ],
  'Support me on Patreon': [
    'Support me on Patreon',
    'Támogass a Patreonon',
    'Apóyame en Patreon',
    'Soutenez-moi sur Patreon',
    'Unterstützen Sie mich auf Patreon',
    'Sostienimi su Patreon',
    'Apoie-me no Patreon',
    'Поддержите меня на Patreon',
    '在Patreon上支持我',
    'Patreonでサポートしてください'
  ]
};


