import 'dart:ui';
import 'ui_helper.dart';

Map<String, String> weatherIconMap = {
  'Clear' : 'clear_night.png',
  'Sunny' : 'sunny.png',
  'Cloudy' : 'cloudy.png',
  'Overcast' : 'cloudy.png',
  'Mist' : 'haze.png',
  'Patchy rain possible' : 'rain.png',
  'Patchy snow possible' : 'snow.png',
  'Patchy sleet possible' : 'sleet.png',
  'Patchy freezing drizzle possible' : 'drizzle.png',
  'Thundery outbreaks possible' : 'lightning.png',
  'Blowing snow' : 'heavy_snow.png',
  'Blizzard' : 'heavy_snow.png',
  'Fog' : 'fog.png',
  'Freezing fog' : 'fog.png',
  'Patchy light drizzle' : 'drizzle.png',
  'Light drizzle' : 'drizzle.png',
  'Freezing drizzle' : 'drizzle.png',
  'Heavy freezing drizzle' : 'drizzle.png',
  'Patchy light rain' : 'drizzle.png',
  'Light rain' : 'drizzle.png',
  'Moderate rain at times' : 'rain.png',
  'Moderate rain' : 'rain.png',
  'Heavy rain at times' : 'heavy_rain.png',
  'Heavy rain' : 'heavy_rain.png',
  'Light freezing rain' : 'sleet.png',
  'Moderate or heavy freezing rain' : 'sleet.png',
  'Light sleet' : 'sleet.png',
  'Moderate or heavy sleet' : 'sleet.png',
  'Patchy light snow' : 'snow.png',
  'Light snow' : 'snow.png',
  'Patchy moderate snow' : 'snow.png',
  'Moderate snow' : 'heavy_snow.png',
  'Patchy heavy snow' : 'heavy_snow.png',
  'Heavy snow' : 'heavy_snow.png',
  'Ice pellets' : 'sleet.png',
  'Light rain shower' : 'drizzle.png',
  'Moderate or heavy rain shower' : 'rain.png',
  'Torrential rain shower' : 'rain.png',
  'Light sleet showers' : 'sleet.png',
  'Moderate or heavy sleet showers' : 'sleet.png',
  'Light snow showers' : 'snow.png',
  'Moderate or heavy snow showers' : 'heavy_snow.png',
  'Light showers of ice pellets' : 'sleet.png',
  'Moderate or heavy showers of ice pellets' : 'sleet.png',
  'Patchy light rain with thunder' : 'lightning.png',
  'Moderate or heavy rain with thunder' : 'lightning.png',
  'Patchy light snow with thunder' : 'lightning.png',
  'Moderate or heavy snow with thunder' : 'lightning.png'
};

Map<String, String> weatherTextMap = {
    'Clear': 'Clear Sky',
    'Sunny': 'Clear Sky',
    'Cloudy': 'Overcast',
    'Partly cloudy': 'Partly Cloudy',
    'Overcast': 'Overcast',
    'Mist': 'Haze',
    'Patchy rain possible': 'Rain',
    'Patchy snow possible': 'Snow',
    'Patchy sleet possible': 'Sleet',
    'Patchy freezing drizzle possible': 'Drizzle',
    'Thundery outbreaks possible': 'Thunderstorm',
    'Blowing snow': 'Heavy Snow',
    'Blizzard': 'Heavy Snow',
    'Fog': 'Fog',
    'Freezing fog': 'Fog',
    'Patchy light drizzle': 'Drizzle',
    'Light drizzle': 'Drizzle',
    'Freezing drizzle': 'Drizzle',
    'Heavy freezing drizzle': 'Drizzle',
    'Patchy light rain': 'Drizzle',
    'Light rain': 'Drizzle',
    'Moderate rain at times': 'Rain',
    'Moderate rain': 'Rain',
    'Heavy rain at times': 'Heavy Rain',
    'Heavy rain': 'Heavy Rain',
    'Light freezing rain': 'Sleet',
    'Moderate or heavy freezing rain': 'Sleet',
    'Light sleet': 'Sleet',
    'Moderate or heavy sleet': 'Sleet',
    'Patchy light snow': 'Snow',
    'Light snow': 'Snow',
    'Patchy moderate snow': 'Snow',
    'Moderate snow': 'Heavy Snow',
    'Patchy heavy snow': 'Heavy Snow',
    'Heavy snow': 'Heavy Snow',
    'Ice pellets': 'Sleet',
    'Light rain shower': 'Drizzle',
    'Moderate or heavy rain shower': 'Rain',
    'Torrential rain shower': 'Rain',
    'Light sleet showers': 'Sleet',
    'Moderate or heavy sleet showers': 'Sleet',
    'Light snow showers': 'Snow',
    'Moderate or heavy snow showers': 'Heavy Snow',
    'Light showers of ice pellets': 'Sleet',
    'Moderate or heavy showers of ice pellets': 'Sleet',
    'Patchy light rain with thunder': 'Thunderstorm',
    'Moderate or heavy rain with thunder': 'Thunderstorm',
    'Patchy light snow with thunder': 'Thunderstorm',
    'Moderate or heavy snow with thunder': 'Thunderstorm'
};

Map<String, String> textBackground = {
  'Clear Night': 'clear_night.jpg',
  'Partly Cloudy': 'cloudy13.jpg',
  'Clear Sky': 'very_clear.jpg',
  'Overcast': 'overcast.jpg',
  'Haze': 'haze.jpg',
  'Rain': 'rainy_sky.jpg',
  'Sleet': 'snowy_sky.jpg',
  'Drizzle': 'drizzle.jpg',
  'Thunderstorm': 'thunderstorm.jpg',
  'Heavy Snow': 'heavy_snow.jpg',
  'Fog': 'fog.jpg',
  'Snow': 'snowy_sky.jpg',
  'Heavy Rain': 'heavy_rain.jpg',
  'Cloudy Night' : 'clear_night_color.jpg'
};

Map<String, List<Color>> textFontColor = {
  'Clear Night': const [BLACK, WHITE],
  'Partly Cloudy': const [WHITE, WHITE],
  'Clear Sky': const [BLACK, WHITE],
  'Overcast': const [BLACK, WHITE],
  'Haze': const [BLACK, WHITE],
  'Rain': const [BLACK, WHITE],
  'Sleet': const [BLACK, WHITE],
  'Drizzle': const [BLACK, WHITE],
  'Thunderstorm': const [BLACK, WHITE],
  'Heavy Snow': const [BLACK, WHITE],
  'Fog': const [BLACK, WHITE],
  'Snow': const [BLACK, WHITE],
  'Heavy Rain': const [BLACK, WHITE],
  'Cloudy Night': const [WHITE, WHITE]
};

Map<int, Color> dayColorMap = {
    1: const Color(0xffD58477),
    2: const Color(0xffA3655B),
    3: const Color(0xffB1D2E1),
    4: const Color(0xff788F99),
    5: const Color(0xffFFFAA0),
    6: const Color(0xffCCC880),
    7: const Color(0xffE1B4BB),
    8: const Color(0xffB49096),
    9: const Color(0xffA9C8A4),
    10: const Color(0xff87A083),
    11: const Color(0xffE5C8DF),
    12: const Color(0xffB7A0B2),
    13: const Color(0xffE1D4BB),
    14: const Color(0xffB4AA96),
};